# Generated by Django 5.2.5 on 2025-11-07 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0003_student_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
