# Generated by Django 5.2.5 on 2025-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0004_issue_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
